### ISSUE TITLE
CI for this repo appears to be permafailing

### ISSUE THREAD

**Issue by phlax** [proxy-wasm/proxy-wasm-cpp-host#386]
While attempting to update rules_rust i got a load of errors

after trying various things i realized that its not my change/s that are throwing the errors, the repo is already permafailing

one of the issues is with installing format deps:

```console
Run cargo install cargo-raze --version 0.14.1
    Updating crates.io index
 Downloading crates ...
  Downloaded cargo-raze v0.14.1
  Installing cargo-raze v0.14.1
    Updating crates.io index
error: failed to compile `cargo-raze v0.14.1`, intermediate artifacts can be found at `/tmp/cargo-install2Nkuax`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  failed to select a version for the requirement `cargo_toml = "^0.8.1"`
  candidate versions found which didn't match: 0.19.2, 0.19.1, 0.19.0, ...
  location searched: crates.io index
  required by package `cargo-raze v0.14.1`
  if you are looking for the prerelease package it needs to be specified explicitly
      cargo_toml = { version = "0.19.0-beta.1" }
  perhaps a crate was updated and forgotten to be re-vendored?
```

macos ci seems to be failing with 

```console
INFO: Repository fuzzing_py_deps instantiated at:
  /Users/runner/work/proxy-wasm-cpp-host/proxy-wasm-cpp-host/WORKSPACE:9:33: in <toplevel>
  /private/var/tmp/_bazel_runner/f7b5b126cb65bf12475e292acf07553d/external/proxy_wasm_cpp_host/bazel/dependencies.bzl:31:23: in proxy_wasm_cpp_host_dependencies
  /private/var/tmp/_bazel_runner/f7b5b126cb65bf12475e292acf07553d/external/rules_fuzzing/fuzzing/init.bzl:23:16: in rules_fuzzing_init
  /private/var/tmp/_bazel_runner/f7b5b126cb65bf12475e292acf07553d/external/rules_python/python/pip.bzl:96:19: in pip_install
Repository rule pip_repository defined at:
  /private/var/tmp/_bazel_runner/f7b5b126cb65bf12475e292acf07553d/external/rules_python/python/pip_install/pip_repository.bzl:276:33: in <toplevel>
Analyzing: 31 targets (103 packages loaded, 68 targets configured)
ERROR: An error occurred during the fetch of repository 'fuzzing_py_deps':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_runner/f7b5b126cb65bf12475e292acf07553d/external/rules_python/python/pip_install/pip_repository.bzl", line 171, column 13, in _pip_repository_impl
		fail("rules_python failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: rules_python failed:  (Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/private/var/tmp/_bazel_runner/f7b5b126cb65bf12475e292acf07553d/external/rules_python/python/pip_install/extract_wheels/__init__.py", line 15, in <module>
    from python.pip_install.extract_wheels.lib import arguments, bazel, requirements
  File "/private/var/tmp/_bazel_runner/f7b5b126cb65bf12475e292acf07553d/external/rules_python/python/pip_install/extract_wheels/lib/bazel.py", line 9, in <module>
    from python.pip_install.extract_wheels.lib import namespace_pkgs, purelib, wheel
  File "/private/var/tmp/_bazel_runner/f7b5b126cb65bf12475e292acf07553d/external/rules_python/python/pip_install/extract_wheels/lib/purelib.py", line 6, in <module>
    from python.pip_install.extract_wheels.lib import wheel
  File "/private/var/tmp/_bazel_runner/f7b5b126cb65bf12475e292acf07553d/external/rules_python/python/pip_install/extract_wheels/lib/wheel.py", line 9, in <module>
    import pkg_resources
  File "/private/var/tmp/_bazel_runner/f7b5b126cb65bf12475e292acf07553d/external/pypi__setuptools/pkg_resources/__init__.py", line 2158, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
)
```

not sure if its due to non-hermetic issues or whether specific change/s have caused it - it seems the last few ci runs on the main branch have likewise failed

**Comment by phlax** [comment]
cc @mpwarres @PiotrSikora

**Comment by phlax** [comment]
just spotted https://github.com/proxy-wasm/proxy-wasm-cpp-host/issues/384 re macos fail

ill give bumping bazel and rules_python a go

**Comment by lum1n0us** [comment]
✋ It seems this issue has been there for months and blocked several PRs. Any updates or plans?

**Comment by martijneken** [comment]
Yep we're working on it, sorry about the state of affairs.

I sent #398 to fix CI itself. The 2 breakages are tracked by these issues:
- macOS: https://github.com/proxy-wasm/proxy-wasm-cpp-host/issues/384
- cargo-raze: https://github.com/proxy-wasm/proxy-wasm-cpp-host/issues/388

Maybe we can close this issue as dupe?

**Comment by phlax** [comment]
up to you - i would keep open until the ci wasnt permafailing - ie as a tracking issue

**Comment by martijneken** [comment]
Almost there, thanks for your patience everyone!

![6yMdiAyMJBgc3nv](https://github.com/user-attachments/assets/d910b68a-7a05-4912-96b8-6ca4317267b6)

**Comment by martijneken** [comment]
Done as of https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/408!
